(OK) Unloading intelmpi 2018.4.274
(!!) no SLURM environment present, environment broken?
(OK) Unloading Intel Suite 19.0.1.144
(OK) Loading gcc system-default
(OK) Intel MPI Suite 2018.4.274 loaded.
(!!) no SLURM environment present, environment broken?
(OK) Loading python 3.8.7
(!!) The SciPy Stack is available: http://www.scipy.org/stackspec.html
 Built with GCC compilers.
(OK) Loading cuda 11.1.1
(!!) We are changing the naming scheme for the CUDA module. cuda/112 will become cuda/11.2 etc. The old version names will soon be deprecated, please update your scripts to avoid problems in the future.
(OK) Loading cudnn 8.0.5
Class ratio used: 10
/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/data/mnist/fed_data/
/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/data/mnist/fed_data/label_flip0/poisoned_0CLs/
[]
/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/data/mnist/fed_data/label_flip0/poisoned_10CLs/
[96 71  8 60 41 94 68  9 19 82]
/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/data/mnist/fed_data/label_flip0/poisoned_20CLs/
[78 81 49 36 27 73 30 52 56  6 35 40 85 84 41 67 91  8 15 21]
/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/data/mnist/fed_data/label_flip0/poisoned_40CLs/
[36 42  9 27 26 78 47 18 25 98 62 86 40 52 37  5 97 75 95 23 58 79 14 72
 33 28 54 87 69 34 80 13 68 61 45  8 22 76 63 71]
Traceback (most recent call last):
  File "run_config.py", line 21, in <module>
    main()
  File "run_config.py", line 17, in main
    start_fl(config)
  File "/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/federated_learning/FL_basic.py", line 937, in start_fl
    cos_defence(clients_selected, poisoned_clients_selected, 0)
  File "/rwthfs/rz/cluster/home/uu852150/repos/CosDefence/federated_learning/FL_basic.py", line 306, in cos_defence
    comp_trusts.append((1+cosine_similarity(comp_vec, agg_val_vector)[0][0])/2)
  File "/home/uu852150/.local/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 1180, in cosine_similarity
    X, Y = check_pairwise_arrays(X, Y)
  File "/home/uu852150/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/uu852150/.local/lib/python3.8/site-packages/sklearn/metrics/pairwise.py", line 146, in check_pairwise_arrays
    X = check_array(X, accept_sparse=accept_sparse, dtype=dtype,
  File "/home/uu852150/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/uu852150/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 734, in check_array
    raise ValueError("Found array with %d feature(s) (shape=%s) while"
ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required by check_pairwise_arrays.
